// This file is generated by rust-protobuf 2.23.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `raid_boss.proto`
use crate::models::Language;
use protobuf::Message;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_23_0;

#[derive(PartialEq,Clone,Default)]
pub struct RaidBoss {
    // message fields
    pub boss_name: ::std::string::String,
    pub level: i32,
    pub image: ::std::string::String,
    pub language: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RaidBoss {
    fn default() -> &'a RaidBoss {
        <RaidBoss as ::protobuf::Message>::default_instance()
    }
}

impl RaidBoss {
    pub fn new() -> RaidBoss {
        ::std::default::Default::default()
    }

    pub fn with_args<S1, S2>(boss_name: S1, level: i32, image: S2, language: Language) -> Self where S1: Into<String>, S2: Into<String> {
        Self {
            boss_name: boss_name.into(),
            level,
            image: image.into(),
            language: language.to_string(),
            unknown_fields: Default::default(),
            cached_size: Default::default()
        }
    }

    // string boss_name = 1;


    pub fn get_boss_name(&self) -> &str {
        &self.boss_name
    }
    pub fn clear_boss_name(&mut self) {
        self.boss_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_boss_name(&mut self, v: ::std::string::String) {
        self.boss_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_boss_name(&mut self) -> &mut ::std::string::String {
        &mut self.boss_name
    }

    // Take field
    pub fn take_boss_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.boss_name, ::std::string::String::new())
    }

    // int32 level = 2;


    pub fn get_level(&self) -> i32 {
        self.level
    }
    pub fn clear_level(&mut self) {
        self.level = 0;
    }

    // Param is passed by value, moved
    pub fn set_level(&mut self, v: i32) {
        self.level = v;
    }

    // string image = 3;


    pub fn get_image(&self) -> &str {
        &self.image
    }
    pub fn clear_image(&mut self) {
        self.image.clear();
    }

    // Param is passed by value, moved
    pub fn set_image(&mut self, v: ::std::string::String) {
        self.image = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_image(&mut self) -> &mut ::std::string::String {
        &mut self.image
    }

    // Take field
    pub fn take_image(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.image, ::std::string::String::new())
    }

    // string language = 4;


    pub fn get_language(&self) -> &str {
        &self.language
    }
    pub fn clear_language(&mut self) {
        self.language.clear();
    }

    // Param is passed by value, moved
    pub fn set_language(&mut self, v: ::std::string::String) {
        self.language = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_language(&mut self) -> &mut ::std::string::String {
        &mut self.language
    }

    // Take field
    pub fn take_language(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.language, ::std::string::String::new())
    }
}

impl ::protobuf::Message for RaidBoss {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.boss_name)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.level = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.image)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.language)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.boss_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.boss_name);
        }
        if self.level != 0 {
            my_size += ::protobuf::rt::value_size(2, self.level, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.image.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.image);
        }
        if !self.language.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.language);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.boss_name.is_empty() {
            os.write_string(1, &self.boss_name)?;
        }
        if self.level != 0 {
            os.write_int32(2, self.level)?;
        }
        if !self.image.is_empty() {
            os.write_string(3, &self.image)?;
        }
        if !self.language.is_empty() {
            os.write_string(4, &self.language)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RaidBoss {
        RaidBoss::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "boss_name",
                |m: &RaidBoss| { &m.boss_name },
                |m: &mut RaidBoss| { &mut m.boss_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "level",
                |m: &RaidBoss| { &m.level },
                |m: &mut RaidBoss| { &mut m.level },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "image",
                |m: &RaidBoss| { &m.image },
                |m: &mut RaidBoss| { &mut m.image },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "language",
                |m: &RaidBoss| { &m.language },
                |m: &mut RaidBoss| { &mut m.language },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RaidBoss>(
                "RaidBoss",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RaidBoss {
        static instance: ::protobuf::rt::LazyV2<RaidBoss> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RaidBoss::new)
    }
}

impl ::protobuf::Clear for RaidBoss {
    fn clear(&mut self) {
        self.boss_name.clear();
        self.level = 0;
        self.image.clear();
        self.language.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RaidBoss {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RaidBoss {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fraid_boss.proto\"o\n\x08RaidBoss\x12\x1b\n\tboss_name\x18\x01\x20\
    \x01(\tR\x08bossName\x12\x14\n\x05level\x18\x02\x20\x01(\x05R\x05level\
    \x12\x14\n\x05image\x18\x03\x20\x01(\tR\x05image\x12\x1a\n\x08language\
    \x18\x04\x20\x01(\tR\x08languageJ\x86\x02\n\x06\x12\x04\0\0\x07\x01\n\
    \x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\x02\x04\0\x12\x04\x02\0\x07\x01\n\n\
    \n\x03\x04\0\x01\x12\x03\x02\x08\x10\n\x0b\n\x04\x04\0\x02\0\x12\x03\x03\
    \x02\x17\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x03\x02\x08\n\x0c\n\x05\x04\
    \0\x02\0\x01\x12\x03\x03\t\x12\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x03\
    \x15\x16\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x04\x02\x12\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\x04\x02\x07\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\
    \x04\x08\r\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x04\x10\x11\n\x0b\n\x04\
    \x04\0\x02\x02\x12\x03\x05\x02\x13\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\
    \x05\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x05\t\x0e\n\x0c\n\x05\
    \x04\0\x02\x02\x03\x12\x03\x05\x11\x12\n\x0b\n\x04\x04\0\x02\x03\x12\x03\
    \x06\x02\x16\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x06\x02\x08\n\x0c\n\
    \x05\x04\0\x02\x03\x01\x12\x03\x06\t\x11\n\x0c\n\x05\x04\0\x02\x03\x03\
    \x12\x03\x06\x14\x15b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
